# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
  RG: 'iac-rg-prod'
  LOCATION: 'UK South'

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Deploy
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: Azure Bicep IaC Deployment
        inputs:
          deploymentScope: 'Subscription'
          azureResourceManagerConnection: 'iac-aad-deploy-dev'
          subscriptionId: '$(SUB_ID)'
          location: '$(LOCATION)'
          templateLocation: 'Linked artifact'
          csmFile: './AzureAppService/main.bicep'
          csmParametersFile: './AzureAppService/main.parameters.json'
          deploymentMode: 'Incremental'
