# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

name: Deploy Azure Bastion Bicep files

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Deploy
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy
      inputs:
        deploymentScope: 'Subscription'
        azureResourceManagerConnection: 'iac-aad-deploy-dev'
        subscriptionId: '031e997d-b908-4dd0-9dba-c440758aec29'
        location: 'UK South'
        templateLocation: 'Linked artifact'
        csmFile: './ResourceGroups/main.bicep'
        csmParametersFile: './ResourceGroups/main.parameters.json'
        deploymentMode: 'Validation'